insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Perth Jandakot Airport', 'cjindra0@vimeo.com', '핌', '2023-01-04', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Sege Airport', 'mbaly1@zdnet.com', '핌', '2022-12-23', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Uroubi Airport', 'mburrage2@baidu.com', '람', '2023-02-13', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Nicaro Airport', 'cnelthorpe3@gmpg.org', '람', '2023-02-26', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Sultan Khairun Babullah Airport', 'swillcox4@tripadvisor.com', '핌', '2022-06-26', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Moanamani Airport', 'sjennemann5@guardian.co.uk', '람', '2022-06-17', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('General José María Yáñez International Airport', 'ltowle6@answers.com', '람', '2023-04-13', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Aba Tenna Dejazmach Yilma International Airport', 'navrahamian7@ted.com', '람', '2022-05-26', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Nuremberg Airport', 'vgarnett8@guardian.co.uk', '람', '2023-03-28', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Pakhokku Airport', 'rkeenleyside9@desdev.cn', '핌', '2023-01-15', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Kokkola-Pietarsaari Airport', 'bbartera@squarespace.com', '핌', '2022-11-23', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Spirit of St Louis Airport', 'dmacintyreb@miitbeian.gov.cn', '람', '2023-01-12', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Mafeteng Airport', 'dcasewellc@privacy.gov.au', '람', '2022-09-15', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('East Midlands Airport', 'mobreend@tripadvisor.com', '핌', '2023-01-12', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Tifalmin Airport', 'zcicchilloe@nasa.gov', '핌', '2023-01-28', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Essen Mulheim Airport', 'fhardingf@dyndns.org', '람', '2022-09-08', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Nkaus Airport', 'aogborneg@canalblog.com', '핌', '2023-03-28', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Abengourou Airport', 'ldukerh@wikipedia.org', '핌', '2023-02-03', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Rock Hill - York County Airport', 'acantoi@huffingtonpost.com', '람', '2023-01-27', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Patrick Air Force Base', 'rfritchlyj@mozilla.org', '핌', '2022-11-07', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('St George Municipal Airport', 'rchatfieldk@java.com', '람', '2022-11-14', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Vaasa Airport', 'wschimannl@symantec.com', '람', '2022-09-04', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Madurai Airport', 'hfrankem@abc.net.au', '람', '2022-05-10', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Gwa Airport', 'bbedelln@sakura.ne.jp', '핌', '2022-12-24', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Novo Horizonte Airport', 'kwilliso@stanford.edu', '람', '2022-07-07', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Nanded Airport', 'tveiversp@usgs.gov', '람', '2023-04-10', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Enyu Airfield', 'ljanekq@cnbc.com', '핌', '2022-06-08', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Sharm El Sheikh International Airport', 'rhaskinsr@cloudflare.com', '핌', '2023-02-10', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Bhadrapur Airport', 'srives@umn.edu', '람', '2022-10-06', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Gordon Downs Airport', 'mshinfieldt@virginia.edu', '람', '2023-03-14', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Chandler Field', 'rgreestu@nasa.gov', '핌', '2022-11-21', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Mount Gambier Airport', 'azaniolettiv@plala.or.jp', '핌', '2022-11-27', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Sodankyla Airport', 'vbadcockw@youtu.be', '핌', '2022-11-28', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Frankfurt am Main Airport', 'nfranex@elpais.com', '람', '2022-11-13', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Bonriki International Airport', 'bvedenyapiny@mlb.com', '핌', '2023-04-22', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Erechim Airport', 'dbazochez@seesaa.net', '람', '2023-01-11', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Miri Airport', 'kspadoni10@cbsnews.com', '람', '2023-03-15', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Mueda Airport', 'mmacmenamy11@europa.eu', '핌', '2022-05-19', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Diego Garcia Naval Support Facility', 'rbalog12@earthlink.net', '핌', '2022-07-11', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Campbellpore Airport', 'njacks13@weebly.com', '람', '2022-11-17', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Hluhluwe Airport', 'lwhittington14@yale.edu', '람', '2023-02-18', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Lesobeng Airport', 'bmcenhill15@sohu.com', '핌', '2022-06-26', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Takamatsu Airport', 'jdowsing16@prweb.com', '핌', '2022-05-24', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Santa Rosa Airport', 'lkenrat17@apple.com', '람', '2022-10-03', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Nakashibetsu Airport', 'mlicence18@tinyurl.com', '람', '2022-06-05', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('St Paul Downtown Holman Field', 'jcoorington19@joomla.org', '핌', '2022-06-24', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Ignace Municipal Airport', 'lgillman1a@jimdo.com', '람', '2023-03-15', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Pablo L. Sidar Airport', 'menos1b@facebook.com', '람', '2022-11-27', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Ouani Airport', 'vbolger1c@princeton.edu', '람', '2023-01-05', '2023-04-23');
insert into practice (prac_title, prac_content, prac_writer, createdate, updatedate) values ('Kemmerer Municipal Airport', 'dwillden1d@vimeo.com', '람', '2023-01-09', '2023-04-23');
